local_backend: true
backend:
  name: git-gateway
  branch: master
collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: src/collections/posts
    create: true
    fields:
      - name: title
        label: Title
      - name: section
        label: Section
        hint: This will decide which section the post appears in on the homepage and article collection pages. The None value is a specialty value to make pages like getting-started editable, but have them not appear in any list.
        widget: select
        options:
          - { label: 'Announcement', value: 'announcements' }
          - { label: 'News', value: 'news' }
          - { label: 'Music Pack', value: 'music-packs' }
          - { label: 'Community Event', value: 'community-events' }
          - { label: 'Map of the Week', value: 'maps-of-the-week' }
          - { label: 'None', value: 'none' }
      - name: publish
        label: Publish Date
        widget: datetime
      - name: homepageText
        label: Homepage Text
        required: false
        hint: This text is used when displaying this post as a component of the homepage. If not provided, the title will be used.
      - name: body
        label: Body
        widget: markdown
      - name: image
        label: Image
        widget: image
        required: false
        media_folder: /static/uploads/posts
        choose_url: false
      - name: author
        label: Author
        widget: relation
        multiple: true
        collection: authors
        search_fields: [name]
        value_field: "{{slug}}"
        display_fields: [name]
        required: true
        hint: The author(s) of this article. You can select multiple! 
  - name: curation-team
    label: Curation Team
    slug: '{{name}}'
    folder: src/collections/curation-team
    create: true
    fields:
      - name: name
      - name: slug
      - name: role
        widget: select
        options: [Curator, Senior Curator]
      - name: style_tags
        widget: list
        allow_add: true
      - name: favorite_map
        widget: object
        fields:
          - name: name
          - name: url
      - name: bio
        widget: markdown
      - name: image
        widget: image
        media_folder: /static/uploads/curators
        choose_url: false
  - name: map-of-the-week
    label: Map of the Week
    folder: src/collections/map-of-the-week
    slug: '{{startDate}}'
    create: true
    fields:
      - name: mapId
        label: Map  ID
        hint: The BeatSaver ID of the map of the week. You can find this one in the URL of the map's page on beatsaver.com. For example, the ID of the map https://beatsaver.com/maps/8f is the last part 8f.
      - name: review
        label: Review
        hint: "An accompanying text to the map of the week that should review and ideally describe what made it the MOTW. Example \"This map has a fantastic lightshow on the new Lattice environment, a poodle diff and three other diffs accessible to a variety of players with great and unique usage of arcs.\""
        widget: text
      - name: startDate
        label: Start Date
        hint: Starting when the map of the week should be displayed on the root page.
        default: 2024-01-01T00:00:00Z
        widget: datetime
      - name: coverUrlOverwrite
        label: Cover URL
        required: false
        hint: If you want to use a different cover image than the one fetched from BeatLeader, you can provide a URL here.
        widget: string
  - name: authors
    label: Authors
    folder: src/collections/authors
    slug: '{{name}}'
    create: true
    fields:
      - name: name
        label: name
      - name: bio
        widget: markdown
        required: false
      - name: image
        widget: image
        media_folder: /static/uploads/authors
        choose_url: false
        required: false
      - name: discord_name
        label: Discord Name
        required: false
      - name: beatsaver_name
        label: BeatSaver Name
        required: false
      - name: beatleader_name
        label: BeatLeader Name
        required: false
media_folder: 'static/uploads'
public_folder: '/uploads'
