local_backend: true
backend:
  name: git-gateway
  branch: master
collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: src/collections/posts
    create: true
    fields:
      - name: title
        label: Title
      - name: section
        label: Section
        hint: This will decide which section the post appears in on the homepage and article collection pages.
        widget: select
        options:
          - { label: 'Announcements', value: 'announcements' }
          - { label: 'Articles', value: 'articles' }
          - { label: 'Speciality', value: 'speciality' }
      - name: category
        label: Category
        hint: This will determine what label will show above the post title.
        widget: select
        options:
          - { label: 'None', value: '' }
          - { label: 'Announcement', value: 'announcement' }
          - { label: 'News', value: 'news' }
          - { label: 'Guide', value: 'guide' }
          - { label: 'Interview', value: 'interview' }
          - { label: 'Event', value: 'event' }
      - name: publish
        label: Publish Date
        widget: datetime
      - name: homepageText
        label: Homepage Text
        required: false
        hint: This text is used when displaying this post as a component of the homepage. If not provided, the title will be used.
      - name: body
        label: Body
        widget: markdown
      - name: image
        label: Image
        widget: image
        required: false
        media_folder: /static/uploads/posts
        choose_url: false
      - name: authors
        label: Author(s)
        widget: relation
        multiple: true
        collection: people
        search_fields: [name]
        value_field: '{{beatsaverId}}'
        display_fields: [name]
        required: true
        hint: The author(s) of this article. You can select multiple, but must select at least one!
      - name: credits
        label: Credits
        required: false
        widget: list
        summary: 'Thanks to {{fields.contributor}} for {{fields.contribution}}.'
        fields:
          - name: contributors
            label: Contributor(s)
            widget: relation
            collection: people
            search_fields: [name]
            value_field: '{{beatsaverId}}'
            display_fields: [name]
            multiple: true
            hint: The contributor(s) of this article. You can select multiple if they have contributed in the same way.
          - name: contribution
            label: Contribution
            widget: string
            hint: "The contribution of the contributor(s) to this article. If provided it will be inserted into the articles as 'Thanks to {{Contributor}} for {{Contribution}}.' If not provided, the contributor's name will be used without any further specification. Example: 'the feedback and proofreading the article'."
            required: false
      - name: showInPostListing
        label: Show in post listing
        widget: boolean
        default: true
  - name: curation-team
    label: Curation Team
    slug: '{{name}}'
    folder: src/collections/curation-team
    create: true
    fields:
      - name: name
      - name: slug
      - name: role
        widget: select
        options: [Curator, Senior Curator]
      - name: style_tags
        widget: list
        allow_add: true
      - name: favorite_map
        widget: object
        fields:
          - name: name
          - name: url
      - name: bio
        widget: markdown
      - name: image
        widget: image
        media_folder: /static/uploads/curators
        choose_url: false
  - name: map-of-the-week
    label: Map of the Week
    folder: src/collections/map-of-the-week
    slug: '{{startDate}}'
    create: true
    fields:
      - name: mapId
        label: Map  ID
        hint: The BeatSaver ID of the map of the week. You can find this one in the URL of the map's page on beatsaver.com. For example, the ID of the map https://beatsaver.com/maps/8f is the last part 8f.
      - name: review
        label: Review
        hint: 'An accompanying text to the map of the week that should review and ideally describe what made it the MOTW. Example "This map has a fantastic lightshow on the new Lattice environment, a poodle diff and three other diffs accessible to a variety of players with great and unique usage of arcs."'
        widget: text
      - name: startDate
        label: Start Date
        hint: Starting when the map of the week should be displayed on the root page.
        default: 2024-01-01T00:00:00Z
        widget: datetime
      - name: coverUrlOverwrite
        label: Cover URL
        required: false
        hint: If you want to use a different cover image than the one fetched from BeatLeader, you can provide a URL here.
        widget: string
  - name: people
    label: People
    folder: src/collections/people
    slug: '{{name}}'
    create: true
    fields:
      - name: name
        label: name
      - name: beatsaverId
        label: BeatSaver ID
        hint: "The BeatSaver ID of the user. You can find this one in the URL of the user's page on beatsaver.com which will look like this: https://beatsaver.com/profile/${beatsaverId}. The ID is the last part of the URL."
      - name: bio
        label: Bio
        widget: markdown
        required: false
        hint: A short bio of the user. Only used for authors on posts.
      - name: socialLinks
        label: Social Links
        widget: list
        multiple: true
        required: false
        hint: The social links of the user. Only used for authors on posts. The BeatSaver ID is given above as well, but if you want this to be listed as your social links you need to re-enter it here.
        summary: '{{fields.platform}}: {{fields.id}}'
        fields:
          - name: platform
            label: Platform
            widget: select
            options:
              - label: BeatSaver
                value: beatsaver
              - label: Discord
                value: discord
          - name: id
            label: ID
            widget: string
media_folder: 'static/uploads'
public_folder: '/uploads'
